name: Build and Test

on: 
  schedule:
    - cron: '0 0 * * SAT'
  push:


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ github.event.schedule == '' && 'stable' || 'nightly' }}
        cache: false

    - uses: Swatinem/rust-cache@v2
      with: 
        shared-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose

  end-to-end:
    name: end-to-end test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ github.event.schedule == '' && 'stable' || 'nightly' }}
        cache: false
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run Rust integration tests
      run: make test

  server-test:
    name: server test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ github.event.schedule == '' && 'stable' || 'nightly' }}
        cache: false
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run server integration tests
      run: cargo test --test test-server --features server

  docker-test:
    name: docker image test
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ github.event.schedule == '' && 'stable' || 'nightly' }}
        cache: false
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Install MUSL tools
      run: |
        sudo apt-get update
        sudo apt-get install musl-tools -y
    - name: Run Docker test
      run: make docker.test